
- name: Initialize Terraform
  hosts: localhost  # Target the localhost
  gather_facts: no  # Set to no if you don’t need facts
  tasks:
    - name: Initialize Terraform
      command: terraform init
      args:
        chdir: ./terraform/main.tf  # Change to your Terraform directory
