- name: Initialize Terraform
  command: terraform init
  args:
    chdir: /path/to/terraform/folder

- name: Apply Terraform
  command: terraform apply -auto-approve
  args:
    chdir: /path/to/terraform/folder
