# .github/workflows/terraform-ansible.yml

name: Terraform and Ansible Automation

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible -y

      - name: Run Ansible Playbook
        run: ansible-playbook ansible/playbook.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
