name: Run Ansible to Trigger Terraform

on:
  push:
    branches:
      - master

jobs:
  ansible-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Ansible Playbook
        run: ansible-playbook ansible-playbook.yml
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
